name: justdolog-dev

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000 