name: justdolog-dev

networks:
  app-tier:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app-tier
    depends_on:
      minio:
        condition: service_healthy
      redis:
        condition: service_started

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    env_file:
      - .env.dev
    environment:
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME:-justdolog-media}:public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-tier
    command: sh -c "apt-get update && apt-get install -y curl && /docker-entrypoint-initdb.d/init-minio.sh & /opt/bitnami/scripts/minio/run.sh"

  redis:
    image: 'redis:7.2-alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./redis.dev.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app-tier
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
  redis_data: 