# Generated by Django 5.1.6 on 2025-02-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_options_postlike_post_liked_by_postread_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
