# Generated by Django 5.1.6 on 2025-02-08 09:09

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자들"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=user.models.profile_image_path,
                verbose_name="프로필 이미지",
            ),
        ),
    ]
