# Generated by Django 5.1.6 on 2025-02-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_facebook_customuser_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_url',
        ),
    ]
